<?php

namespace WebCrawlerBundle\Repository;

/**
 * URLsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class URLsRepository extends \Doctrine\ORM\EntityRepository
{
}
